# Generated by Django 2.1 on 2018-10-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'ordering': ['number_of_image'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
