# Generated by Django 2.1 on 2018-10-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20181007_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Free'), ('1', 'Booked'), ('2', 'Disable')], default='0', max_length=1)),
                ('date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
            ],
            options={
                'verbose_name': 'Date statuses',
                'verbose_name_plural': 'Dates statuses',
            },
        ),
    ]
