# Generated by Django 2.1 on 2018-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartmentdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdates',
            name='status',
            field=models.CharField(choices=[('0', 'Disable'), ('1', 'Free')], default='1', max_length=1),
        ),
    ]
