# Generated by Django 2.1 on 2018-10-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20181009_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartmentdates',
            unique_together={('date', 'apartment')},
        ),
    ]
