# Generated by Django 2.1 on 2018-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_auto_20181118_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
