# Generated by Django 2.1 on 2018-11-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20181118_1257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartmentdates',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='apartmentdates',
            name='apartment',
        ),
        migrations.DeleteModel(
            name='ApartmentDates',
        ),
    ]
