# Generated by Django 2.1 on 2018-12-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_auto_20181118_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image_main',
        ),
    ]
