# Generated by Django 2.1 on 2018-11-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_auto_20181118_2151'),
        ('reservations', '0002_auto_20181005_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Disable'), ('1', 'Booked')], default='0', max_length=1)),
                ('date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
                ('reservation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Reservation')),
            ],
            options={
                'verbose_name': 'Reserved date',
                'verbose_name_plural': 'Reserved dates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reserveddates',
            unique_together={('date', 'apartment')},
        ),
    ]
