# Generated by Django 2.1 on 2018-11-18 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenuLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('url', models.TextField(max_length=128, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Navigation menu link',
                'verbose_name_plural': 'Navigation menu links',
            },
        ),
    ]
