# Generated by Django 2.1 on 2018-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181118_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenulinks',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
